name: ASCIIbrot
description: generates a mandelbrot set rendered in beautiful ASCII
dependencies:
  browser: any
  viltage:
    git:
      ref: 141872d37ae64aab72e3f915ca670f5e660ab174
      url: https://github.com/ViliX64/VilTAGE.git
